name: "Business Greeting"
description: "Offers professional greetings and timestamps them"
inputs:
  name:
    description: 'Name of the person or team to greet'
    required: true
    default: 'Udacity Learner'
outputs:
  timestamp:
    description: 'Time of greeting'
runs:
  using: 'composite'
  steps:
    - name: Checkout Action Repository
      uses: actions/checkout@v4
      with:
        path: action_repo  # Clones into a subdirectory

    - name: Run Python Script
      run: python action_repo/main.py
      shell: bash
